#!/bin/bash

clear

# 检查pvf
if [ ! -f /home/neople/game/Script.pvf ]; then
    echo "Script.pvf 不存在!!!"
    exit
fi
# 检查df_game_r
if [ ! -f /home/neople/game/df_game_r ]; then
    echo "df_game_r 不存在!!!"
    exit
fi
# 检查publickey.pem
if [ ! -f /home/neople/game/publickey.pem ]; then
    echo "publickey.pem 不存在!!!"
    exit
fi

cd /home/neople/channel
chmod -R 755 *
rm -f /home/neople/channel/pid/*.pid
rm -rf /home/neople/channel/log/*
LD_PRELOAD=/lib/libhook.so ./df_channel_r channel start &

cd /home/neople/relay
chmod -R 755 *
rm -f /home/neople/relay/pid/*.pid
rm -rf /home/neople/relay/log/*
./df_relay_r relay_200 start &

cd /home/neople/stun
chmod -R 755 *
rm -f /home/neople/stun/pid/*.pid
rm -rf /home/neople/stun/log/*
./df_stun_r start &

cd /home/neople/manager
chmod -R 755 *
rm -f /home/neople/manager/pid/*.pid
rm -rf /home/neople/manager/log/*
LD_PRELOAD=/lib/libhook.so ./df_manager_r manager start &

cd /home/neople/bridge
chmod -R 755 *
rm -f /home/neople/bridge/pid/*.pid
rm -rf /home/neople/bridge/log/*
LD_PRELOAD=/lib/libhook.so ./df_bridge_r bridge start &

cd /home/neople/community
chmod -R 755 *
rm -f /home/neople/community/pid/*.pid
rm -rf /home/neople/community/log/*
./df_community_r community start &

cd /home/neople/coserver
chmod -R 755 *
rm -f /home/neople/coserver/pid/*.pid
rm -rf /home/neople/coserver/log/*
LD_PRELOAD=/lib/libhook.so ./df_coserver_r coserver start &

# 拍卖行
cd /home/neople/auction
chmod 755 *
rm -f /home/neople/auction/pid/*.pid
rm -rf /home/neople/auction/log/*.*
./df_auction_r ./cfg/auction_siroco.cfg start ./df_auction_r &

# 金币寄存
cd /home/neople/point
chmod 755 *
rm -f /home/neople/point/pid/*.pid
rm -rf /home/neople/point/log/*.*
./df_point_r ./cfg/point_siroco.cfg start df_point_r &

cd /home/neople/dbmw_mnt
chmod -R 755 *
rm -f /home/neople/dbmw_mnt/pid/*.pid
rm -rf /home/neople/dbmw_mnt/log/*
LD_PRELOAD=/lib/libhook.so ./df_dbmw_r dbmw_mnt_siroco start &

cd /home/neople/dbmw_stat
chmod -R 755 *
rm -f /home/neople/dbmw_stat/pid/*.pid
rm -rf /home/neople/dbmw_stat/log/*
LD_PRELOAD=/lib/libhook.so ./df_dbmw_r dbmw_stat_siroco start &

cd /home/neople/dbmw_guild
chmod -R 755 *
rm -f /home/neople/dbmw_guild/pid/*.pid
rm -rf /home/neople/dbmw_guild/log/*
LD_PRELOAD=/lib/libhook.so ./df_dbmw_r dbmw_gld_siroco start &

# 公会
cd /home/neople/guild
chmod 755 *
rm -f /home/neople/guild/pid/*.pid
rm -rf /home/neople/guild/log/*.*
LD_PRELOAD=/lib/libhook.so ./df_guild_r gld_siroco start &

cd /home/neople/monitor
chmod -R 755 *
rm -f /home/neople/monitor/pid/*.pid
rm -rf /home/neople/monitor/log/*
LD_PRELOAD=/lib/libhook.so ./df_monitor_r mnt_siroco start &

cd /home/neople/statics
chmod -R 755 *
rm -f /home/neople/statics/pid/*.pid
rm -rf /home/neople/statics/log/*
LD_PRELOAD=/lib/libhook.so ./df_statics_r stat_siroco start &

cd /home/neople/secsvr/gunnersvr
chmod -R 755 *
rm -rf /home/neople/secsvr/gunnersvr/log/*
rm -f /home/neople/secsvr/gunnersvr/*.pid
./gunnersvr -t30 -i1 &

cd /home/neople/secsvr/zergsvr
chmod -R 755 *
rm -rf /home/neople/secsvr/zergsvr/log/*
rm -f /home/neople/secsvr/zergsvr/*.pid

./secagent &
./zergsvr -t30 -i1 &

sleep 2
cd /home/neople/game
chmod -R 755 *
rm -rf /home/neople/game/log/*
rm -rf /home/neople/game/pid/*
# LD_PRELOAD=/dp2/libdp2pre.so ./df_game_r siroco11 start &
LD_PRELOAD=/lib/libhook.so ./df_game_r cain11 start &
