#! /bin/bash

echo "Channel Restart..."
killall -9 df_channel_r
sleep 2

cd /home/neople/channel
LD_PRELOAD=/lib/libhook.so ./df_channel_r channel start &
echo "================================Channel 		Srv Start"
