#!/bin/bash

killall -9 df_game_r
killall -9 gunnersvr
killall -9 zergsvr
killall -9 secagent

sleep 1
cd /home/neople/guild
chmod 755 *
./df_guild_r guild stop

sleep 2
cd /home/neople/monitor
chmod -R 755 *
./df_monitor_r monitor stop

sleep 2
cd /home/neople/statics
chmod -R 755 *
./df_statics_r statics stop

sleep 2
cd /home/neople/dbmw_mnt
chmod -R 755 *
./df_dbmw_r dbmw_mnt stop

sleep 2
cd /home/neople/dbmw_stat
chmod -R 755 *
./df_dbmw_r dbmw_stat stop

sleep 2
cd /home/neople/dbmw_guild
chmod -R 755 *
./df_dbmw_r dbmw_guild stop

sleep 3
cd /home/neople/point
chmod 755 *
./df_point_r ./cfg/point.cfg stop df_point_r

sleep 2
cd /home/neople/auction
chmod 755 *
./df_auction_r ./cfg/auction.cfg stop df_auction_r

sleep 3
cd /home/neople/manager
chmod -R 755 *
./df_manager_r manager stop

sleep 2
cd /home/neople/bridge
chmod -R 755 *
./df_bridge_r bridge stop

sleep 2
cd /home/neople/community
chmod -R 755 *
./df_community_r community stop

sleep 2
cd /home/neople/coserver
chmod -R 755 *
./df_coserver_r coserver stop

sleep 3
cd /home/neople/stun
chmod -R 755 *
./df_stun_r stop

sleep 2
cd /home/neople/relay
chmod -R 755 *
./df_relay_r relay_200 stop

sleep 2
cd /home/neople/channel
chmod -R 755 *
./df_channel_r channel stop

sleep 3

find /home/neople \( -name "*.log" -o -name "*.pid" -o -name "core.*" \) -type f -print -exec rm -f {} \;
