#!/bin/bash

# absolute path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd $SCRIPT_DIR

find . -name ".DS_Store" -type f -delete

# MySQL
cd $SCRIPT_DIR/MySQL
tar -czvf MySQL.tar.gz \
    ./etc \
    ./root
mv MySQL.tar.gz $SCRIPT_DIR

# Gateway
cd $SCRIPT_DIR/Gateway
tar -czvf Gateway.tar.gz \
    ./home \
    ./root \
    ./usr
mv Gateway.tar.gz $SCRIPT_DIR

# Game
cd $SCRIPT_DIR/Game
tar -czvf Game.tar.gz \
    ./dp2 \
    ./home \
    ./root \
    ./usr
mv Game.tar.gz $SCRIPT_DIR
